### PR TITLE
3 30 cosmic

### PR DESCRIPTION
**Pull request by isantop**
See #51 

This PR fixes pop-os/pop#361 for Cosmic

### CODE REVIEW

**Comment by jackpot51** [comment]
Do you want to add the symbolic icons to this?

**Comment by isantop** [comment]
I added symbolic icons to the branch with the dialog button changes. That will be PRd as soon as this one is in.

**Comment by brs17** [comment]
I am not sure how this fixes 
https://github.com/pop-os/pop/issues/361 since that seems to have to do with disk encryption issues: 

google translate:
```
Disk encryption often has problems:

1. Sometimes stuck during the boot process. 2. Press the wrong button when entering the password to return to the command line. 3. The password cannot be set without special characters without prompting.

```

**Comment by brs17** [comment]
Was unable to test this patch due to: https://github.com/pop-os/gnome-shell-theme/pull/51#issuecomment-429188133

**Comment by jackpot51** [comment]
The volume overlay does not work correctly

**Pull request merged**
