### PR TITLE
fix dashboard app icon padding

### LINKED ISSUE #41: Dash apps icon padding is too large
What it looks like:
capture d ecran de 2018-08-21 22-58-25

What it should look like:
capture d ecran de 2018-08-21 23-03-14

Regression was introduced by #35:

```css
.show-apps-icon {
  padding: 8px;
}
```

### PR DESCRIPTION
**Pull request by letheed**
Closes #41.

### CODE REVIEW

**Comment by isantop** [comment]
screenshot from 2018-08-27 11-08-53

Example of the problem noted.

**Comment by isantop** [comment]
Can you send in a screenshot of your dock in the setup you have?

**Comment by letheed** [comment]
Here is the default pop dark slim from the ppa:
capture d ecran de 2018-08-27 21-42-40

Now with padding removed/set to 0:
capture d ecran de 2018-08-27 21-44-09

I'm not sure where your right shift comes from, but I'm inclined to think that's the actual problem that need a fix. But the current "fix" breaks the theme for a lot of users. And none of the other gnome-shell themes I've checked set the show-apps-icon padding at all.

**Comment by isantop** [comment]
Set up the dock on the side (left or right edge) of the display. I think you'll see the offset there.

**Comment by isantop** [comment]
Is this the Pop GNOME shell theme? The panel appears to have a gradient on it.

**Comment by letheed** [comment]
On 18.04, I created a new user account, picked 'Ubuntu' (so the default Xorg session) in gdm, enabled shell extensions, enabled the user theme extension, cloned the repo, installed the theme following instructions in README (ppa is purged, and I follow the cleanup instructions first), and picked Pop.

capture d ecran de 2018-08-28 19-20-53

Also the bug with menus that others have reported before is there too.

capture d ecran de 2018-08-28 19-21-27

**Comment by isantop** [comment]
The padding for the show-apps button is, for whatever reason, different depending on whether you use a Pop_OS session or an Ubuntu/GNOME session. :man_facepalming: 

I've made some changes proposed in #44 that should fix it in most cases. Closing this one for now because it actively breaks the Pop_OS session.

**Pull request closed without merging**
