### PR TITLE
Update Switch appearance

### PR DESCRIPTION
**Pull request by isantop**
On 3.30 we want to match the switches on version 4 of the GTK theme.

Fixes pop-os/gtk-theme#226

### CODE REVIEW

**Comment by isantop** [comment]
@brs17 Addressed

**Comment by isantop** [comment]
No it isn't, this will require re-drawing the assets again.

**Comment by isantop** [comment]
Should be gtg now

**Comment by evertiro** [comment]
screenshot from 2018-11-02 20-02-33

Verified that the latest change by @isantop fixed the alignment issue.

**Comment by evertiro** [comment]
Should also mention that I've tested enabling and disabling it and the text maintains alignment.

**Pull request merged**
